/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.cyclestreets;

public final class R {
    public static final class array {
        public static final int mapstyle=0x7f060006;
        public static final int mapstyle_values=0x7f060007;
        public static final int point_type=0x7f060009;
        public static final int point_type3=0x7f060008;
        public static final int routetype=0x7f060002;
        public static final int routetype_values=0x7f060003;
        public static final int speed=0x7f060004;
        public static final int speed_values=0x7f060005;
        public static final int unit_values=0x7f060001;
        public static final int units=0x7f060000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int bear_left=0x7f020000;
        public static final int bear_right=0x7f020001;
        public static final int btn_minus=0x7f020002;
        public static final int btn_next=0x7f020003;
        public static final int btn_plus=0x7f020004;
        public static final int btn_previous=0x7f020005;
        public static final int cyclestreets=0x7f020006;
        public static final int direction_arrow=0x7f020007;
        public static final int double_back=0x7f020008;
        public static final int empty=0x7f020009;
        public static final int footprints=0x7f02000a;
        public static final int green_wisp_36x30=0x7f02000b;
        public static final int ic_input_get=0x7f02000c;
        public static final int ic_menu_agenda=0x7f02000d;
        public static final int ic_menu_camera=0x7f02000e;
        public static final int ic_menu_directions=0x7f02000f;
        public static final int ic_menu_gallery=0x7f020010;
        public static final int ic_menu_info_details=0x7f020011;
        public static final int ic_menu_mapmode=0x7f020012;
        public static final int ic_menu_mylocation=0x7f020013;
        public static final int ic_menu_places=0x7f020014;
        public static final int ic_menu_reverse_directions=0x7f020015;
        public static final int ic_menu_revert=0x7f020016;
        public static final int ic_menu_rotate=0x7f020017;
        public static final int ic_menu_search=0x7f020018;
        public static final int ic_tab_addphoto=0x7f020019;
        public static final int ic_tab_itinerary=0x7f02001a;
        public static final int ic_tab_photomap=0x7f02001b;
        public static final int ic_tab_planroute=0x7f02001c;
        public static final int ic_tab_planroute_grey=0x7f02001d;
        public static final int ic_tab_planroute_white=0x7f02001e;
        public static final int icon=0x7f02001f;
        public static final int marker_default=0x7f020020;
        public static final int marker_default_focused_base=0x7f020021;
        public static final int mm_20_bike=0x7f020022;
        public static final int mm_20_black=0x7f020023;
        public static final int mm_20_car_parking=0x7f020024;
        public static final int mm_20_cone=0x7f020025;
        public static final int mm_20_congestion=0x7f020026;
        public static final int mm_20_cycleway=0x7f020027;
        public static final int mm_20_destination=0x7f020028;
        public static final int mm_20_directional_signage=0x7f020029;
        public static final int mm_20_enforcement=0x7f02002a;
        public static final int mm_20_general_sign=0x7f02002b;
        public static final int mm_20_obstruction=0x7f02002c;
        public static final int mm_20_road=0x7f02002d;
        public static final int mm_20_roadworks=0x7f02002e;
        public static final int mm_20_sheffield_stands=0x7f02002f;
        public static final int mm_20_spanner=0x7f020030;
        public static final int mm_20_white_wisp=0x7f020031;
        public static final int next=0x7f020032;
        public static final int person=0x7f020033;
        public static final int pressed=0x7f020034;
        public static final int previous=0x7f020035;
        public static final int radio_background=0x7f020036;
        public static final int red_button=0x7f020037;
        public static final int red_wisp_36x30=0x7f020038;
        public static final int roundrect=0x7f020039;
        public static final int route_balanced=0x7f02003a;
        public static final int route_balanced_off=0x7f02003b;
        public static final int route_balanced_on=0x7f02003c;
        public static final int route_bg=0x7f02003d;
        public static final int route_fast=0x7f02003e;
        public static final int route_fast_off=0x7f02003f;
        public static final int route_fast_on=0x7f020040;
        public static final int route_quiet=0x7f020041;
        public static final int route_quiet_off=0x7f020042;
        public static final int route_quiet_on=0x7f020043;
        public static final int selected=0x7f020044;
        public static final int sharp_left=0x7f020045;
        public static final int sharp_right=0x7f020046;
        public static final int straight_on=0x7f020047;
        public static final int turn_left=0x7f020048;
        public static final int turn_right=0x7f020049;
        public static final int unselected=0x7f02004a;
        public static final int x_marks_spot=0x7f02004b;
    }
    public static final class id {
        public static final int about_button=0x7f0a0014;
        public static final int addphoto_text=0x7f0a0000;
        public static final int addphoto_text2=0x7f0a0001;
        public static final int caption=0x7f0a0005;
        public static final int category=0x7f0a0007;
        public static final int chooseexisting_button=0x7f0a0003;
        public static final int donate_view=0x7f0a0015;
        public static final int find_place=0x7f0a000c;
        public static final int mapholder=0x7f0a0008;
        public static final int metacat=0x7f0a0006;
        public static final int next=0x7f0a0009;
        public static final int optionsFrom=0x7f0a0018;
        public static final int optionsTo=0x7f0a0019;
        public static final int photo=0x7f0a0004;
        public static final int photo_text=0x7f0a001f;
        public static final int place=0x7f0a000b;
        public static final int routeBalanced=0x7f0a001c;
        public static final int routeFastest=0x7f0a001d;
        public static final int routeFrom=0x7f0a0016;
        public static final int routeGo=0x7f0a001e;
        public static final int routeQuietest=0x7f0a001b;
        public static final int routeTo=0x7f0a0017;
        public static final int routeTypeGroup=0x7f0a001a;
        public static final int route_title=0x7f0a0020;
        public static final int savedroutes=0x7f0a0021;
        public static final int segment_cumulative_distance=0x7f0a0011;
        public static final int segment_distance=0x7f0a0010;
        public static final int segment_street=0x7f0a000e;
        public static final int segment_time=0x7f0a000f;
        public static final int segment_type=0x7f0a000d;
        public static final int settings_button=0x7f0a0013;
        public static final int splash=0x7f0a0012;
        public static final int takephoto_button=0x7f0a0002;
        public static final int webview=0x7f0a000a;
    }
    public static final class layout {
        public static final int addphoto=0x7f030000;
        public static final int addphotocaption=0x7f030001;
        public static final int addphotocategory=0x7f030002;
        public static final int addphotolocation=0x7f030003;
        public static final int addphotonext=0x7f030004;
        public static final int addphotoview=0x7f030005;
        public static final int category_item=0x7f030006;
        public static final int findplace=0x7f030007;
        public static final int geo_item_2line=0x7f030008;
        public static final int itinerary_item=0x7f030009;
        public static final int main=0x7f03000a;
        public static final int more=0x7f03000b;
        public static final int route=0x7f03000c;
        public static final int showphoto=0x7f03000d;
        public static final int storedroutes=0x7f03000e;
        public static final int storedroutes_item=0x7f03000f;
    }
    public static final class menu {
        public static final int toplevel_menu=0x7f090000;
    }
    public static final class raw {
        public static final int mykeystore=0x7f050000;
    }
    public static final class string {
        public static final int about=0x7f07000e;
        public static final int app_name=0x7f07000a;
        public static final int base=0x7f070004;
        public static final int btn_cancel=0x7f07002d;
        /**  find place dialog 
         */
        public static final int btn_find_place=0x7f070029;
        public static final int choose_end=0x7f070016;
        public static final int choose_from=0x7f070013;
        public static final int choose_start=0x7f070015;
        public static final int choose_to=0x7f070014;
        public static final int cloudmade_alternative=0x7f070009;
        public static final int cloudmade_small=0x7f070007;
        public static final int cloudmade_standard=0x7f070008;
        public static final int credits=0x7f07000d;
        public static final int cyclemap=0x7f070002;
        public static final int donate=0x7f070024;
        public static final int error_route=0x7f07001c;
        public static final int finding_route=0x7f070017;
        public static final int geocoding=0x7f07001e;
        public static final int go=0x7f070012;
        public static final int hills=0x7f070006;
        /**  Map menu 
         */
        public static final int ic_menu_directions=0x7f070025;
        public static final int ic_menu_findplace=0x7f070027;
        public static final int ic_menu_mylocation=0x7f070026;
        public static final int ic_menu_saved_routes=0x7f070028;
        public static final int lbl_choose_place=0x7f07002b;
        public static final int lbl_no_place=0x7f07002c;
        public static final int lbl_place=0x7f07002a;
        public static final int loading_route=0x7f070018;
        public static final int mapnik=0x7f070001;
        public static final int my_location=0x7f07001d;
        public static final int no_from=0x7f070021;
        public static final int no_to=0x7f070022;
        public static final int not_found=0x7f07001b;
        public static final int openareal_sat=0x7f070003;
        public static final int osmarender=0x7f070000;
        public static final int please_wait=0x7f07001a;
        public static final int route_failed=0x7f070023;
        public static final int route_from=0x7f070010;
        public static final int route_to=0x7f070011;
        public static final int savedroutes=0x7f07000b;
        public static final int select_route_end=0x7f070020;
        public static final int select_route_start=0x7f07001f;
        public static final int settings=0x7f07000c;
        public static final int topo=0x7f070005;
        public static final int unknown=0x7f07000f;
        public static final int uploading_photo=0x7f070019;
    }
    public static final class style {
        public static final int Theme_Menu=0x7f080001;
        public static final int Theme_Photo=0x7f080002;
        public static final int Theme_RouteInputDialog=0x7f080000;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
